### ISSUE TITLE
Not able to run in windows

### ISSUE THREAD

**Issue by anitalpatil** [kucharzyk/spring-angular2-starter#53]
Amazing project!! Actually I am looking for the microservice project with angular 2 integrated one and fortunatly i got this project. Thank you. 

But the thing is it is not working for me am using windows system. when i give 'mvn install' it is giving error,I checked with docker installation too. it installed properly and other projects with docker are working fine and also i checked with giving 'mvn clean package -P prod-standalone' even this is not working for me(in fact i checked with both production and development commands). can you suggest me where am lacking behind.

**Comment by kucharzyk** [comment]
Hi. Could you provide your build log with errors?

**Comment by anitalpatil** [comment]
Firstly thanks for the reply, when I give 'mvn install' am getting the following log

[INFO] shardis ............................................ SUCCESS [  2.765 s]
[INFO] shardis-common ..................................... SUCCESS [  9.278 s]
[INFO] shardis-discovery .................................. FAILURE [ 14.707 s]
[INFO] shardis-auth ....................................... SKIPPED
[INFO] shardis-gateway .................................... SKIPPED
[INFO] shardis-ui ......................................... SKIPPED
[INFO] shardis-api ........................................ SKIPPED
[INFO] shardis-config ..................................... SKIPPED
[INFO] shardis-admin ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.691 s
[INFO] Finished at: 2017-07-09T19:46:33+05:30
[INFO] Final Memory: 41M/413M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build-image) on project shardis-discovery: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :shardis-discovery

**Comment by anitalpatil** [comment]
When i give 'mvn clean package -P prod-standalone' am getting following build log. Kindly go through it and let me know.

[INFO] --- frontend-maven-plugin:1.0:npm (npm build) @ shardis-ui ---
[INFO] Running 'npm run build:prod' in D:\Anita\spring-angular2-starter-master\shardis-ui
[INFO]
[INFO] > shardis-ui@0.0.0 prebuild:prod D:\Anita\spring-angular2-starter-master\shardis-ui
[INFO] > npm run clean:dist
[INFO]
[INFO]
[INFO] > shardis-ui@0.0.0 clean:dist D:\Anita\spring-angular2-starter-master\shardis-ui
[INFO] > rimraf typings src/main/resources/static/*
[INFO]
[INFO]
[INFO] > shardis-ui@0.0.0 build:prod D:\Anita\spring-angular2-starter-master\shardis-ui
[INFO] > ng build -prod
[INFO]
[INFO] Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
[INFO] Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
[INFO]     at Object.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\@ngtools\webpack\src\index.js:27:11)
[INFO]     at Module._compile (module.js:556:32)
[INFO]     at Object.Module._extensions..js (module.js:565:10)
[INFO]     at Module.load (module.js:473:32)
[INFO]     at tryModuleLoad (module.js:432:12)
[INFO]     at Function.Module._load (module.js:424:3)
[INFO]     at Module.require (module.js:483:17)
[INFO]     at require (internal/module.js:20:19)
[INFO]     at Object.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\models\webpack-build-typescript.js:5:17)
[INFO]     at Module._compile (module.js:556:32)
[INFO]     at Object.Module._extensions..js (module.js:565:10)
[INFO]     at Module.load (module.js:473:32)
[INFO]     at tryModuleLoad (module.js:432:12)
[INFO]     at Function.Module._load (module.js:424:3)
[INFO]     at Module.require (module.js:483:17)
[INFO]     at require (internal/module.js:20:19)
[INFO]     at Object.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\models\webpack-config.js:2:34)
[INFO]     at Module._compile (module.js:556:32)
[INFO]     at Object.Module._extensions..js (module.js:565:10)
[INFO]     at Module.load (module.js:473:32)
[INFO]     at tryModuleLoad (module.js:432:12)
[ERROR]
[INFO]     at Function.Module._load (module.js:424:3)
[INFO]     at Module.require (module.js:483:17)
[INFO]     at require (internal/module.js:20:19)
[INFO]     at Object.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\tasks\build-webpack.js:6:24)
[INFO]     at Module._compile (module.js:556:32)
[INFO]     at Object.Module._extensions..js (module.js:565:10)
[INFO]     at Module.load (module.js:473:32)
[INFO]     at tryModuleLoad (module.js:432:12)
[INFO]     at Function.Module._load (module.js:424:3)
[INFO]     at Module.require (module.js:483:17)
[INFO]     at require (internal/module.js:20:19)
[INFO]     at Object.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\commands\build.js:3:23)
[INFO]     at Module._compile (module.js:556:32)
[ERROR] npm ERR! Windows_NT 10.0.14393
[INFO]     at Object.Module._extensions..js (module.js:565:10)
[ERROR] npm ERR! argv "D:\\Anita\\spring-angular2-starter-master\\shardis-ui\\node\\node.exe" "D:\\Anita\\spring-angular2-starter-master\\shardis-ui\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
[INFO]     at Module.load (module.js:473:32)
[ERROR] npm ERR! node v6.7.0
[INFO]     at tryModuleLoad (module.js:432:12)
[ERROR] npm ERR! npm  v3.10.3
[INFO]     at Function.Module._load (module.js:424:3)
[ERROR] npm ERR! code ELIFECYCLE
[INFO]     at Module.require (module.js:483:17)
[ERROR] npm ERR! shardis-ui@0.0.0 build:prod: `ng build -prod`
[INFO]     at require (internal/module.js:20:19)
[ERROR] npm ERR! Exit status 1
[INFO]     at Class.includedCommands (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\addon\index.js:21:16)
[ERROR] npm ERR!
[INFO]     at D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\lib\models\project.js:392:61
[INFO]     at Array.forEach (native)
[INFO]     at Project.addonCommands (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\lib\models\project.js:391:15)
[ERROR] npm ERR! Failed at the shardis-ui@0.0.0 build:prod script 'ng build -prod'.
[INFO]     at Project.eachAddonCommand (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\lib\models\project.js:426:30)
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[INFO]     at module.exports (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
[ERROR] npm ERR! If you do, this is most likely a problem with the shardis-ui package,
[ERROR] npm ERR! not with npm itself.
[INFO]     at CLI.<anonymous> (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\angular-cli\lib\cli\cli.js:34:26)
[ERROR] npm ERR! Tell the author that this fails on your system:
[INFO]     at tryCatch (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\rsvp\dist\rsvp.js:525:12)
[ERROR] npm ERR!     ng build -prod
[INFO]     at invokeCallback (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\rsvp\dist\rsvp.js:538:13)
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[INFO]     at publish (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\rsvp\dist\rsvp.js:508:7)
[ERROR] npm ERR!     npm bugs shardis-ui
[INFO]     at flush (D:\Anita\spring-angular2-starter-master\shardis-ui\node_modules\rsvp\dist\rsvp.js:2400:5)
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[INFO]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[ERROR] npm ERR!     npm owner ls shardis-ui
[INFO]     at process._tickCallback (internal/process/next_tick.js:98:9)
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     D:\Anita\spring-angular2-starter-master\shardis-ui\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] shardis ............................................ SUCCESS [  0.723 s]
[INFO] shardis-common ..................................... SUCCESS [  6.813 s]
[INFO] shardis-discovery .................................. SUCCESS [  1.867 s]
[INFO] shardis-auth ....................................... SUCCESS [ 10.742 s]
[INFO] shardis-gateway .................................... SUCCESS [  1.077 s]
[INFO] shardis-ui ......................................... FAILURE [ 30.939 s]
[INFO] shardis-api ........................................ SKIPPED
[INFO] shardis-config ..................................... SKIPPED
[INFO] shardis-admin ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.771 s
[INFO] Finished at: 2017-07-09T19:53:05+05:30
[INFO] Final Memory: 63M/356M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm build) on project shardis-ui: Failed to run task: 'npm run build:prod' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :shardis-ui

**Comment by kucharzyk** [comment]
First error is problem with docker - It looks like spotify docker maven plugin can't connect to your docker instance. 

Please check is docker runnning ```docker -ps```

**Comment by kucharzyk** [comment]
Second error is problem with webpack and angular-cli - try generate new project with angular-cli and update dependencies in package.json

**Comment by raghu502** [comment]
Hi ,I am facing below issue.
can you please any one help on that.

loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
(node:3396) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Hash: b38e1dcc0defb22b6f6b
Time: 20127ms
chunk    {0} main.bundle.js, main.bundle.map (main) 41.4 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 128 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 3.7 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in Error: Could not resolve "app/about/about.module" from "E:/karvy_projects/angular/ui-application3/src/main/frontend/app/app-routing.module.ts".
    at _resolveModule (E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:78:15)
    at E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:32
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:107:54)
    at E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:117:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:116:10)
    at Object.listLazyRoutesOfModule (E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_impl.js:52:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (E:\karvy_projects\angular\ui-application3\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:39)
    at AotPlugin._getLazyRoutesFromNgtools (E:\karvy_projects\angular\ui-application3\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (E:\karvy_projects\angular\ui-application3\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: Failed to compile.
